config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/home'
  resource :dashboard, only: [:show] do
    collection do
      get 'search'
    end
  end
  resource :profile, only: %i[new show edit create update]
end

app/models/profile.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
require 'csv'
class Profile < ApplicationRecord
  belongs_to :user
  has_one :address, dependent: :destroy
  has_many :hobbies, dependent: :destroy

  accepts_nested_attributes_for :address, allow_destroy: true
  accepts_nested_attributes_for :hobbies, reject_if: :all_blank, allow_destroy: true
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to dashboard_path, notice: 'Profile created successfully.'
    else
      render :new
    end
  end

  def edit
    @profile = current_user.profile.present? ? current_user.profile : current_user.build_profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to dashboard_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :first_name,
      :last_name,
      address_attributes: %i[id city],
      hobbies_attributes: %i[id name]
    )
  end
end

app/views/profiles/edit.html.erb
<h3 class="mb-5">Profile bearbeiten</h3>

<%= form_for setup_profile(@profile), url: profile_path do |f| %>
  <h5 class="mb-5">Addresse</h4>
  <%= f.fields_for :address do |ff| %>
    <div class="field">
      <%= ff.label :city, "Wohnort", class: "label" %>
      <%= ff.text_field :city, hint: 'No special characters.', class: "input" %>
    </div>
  <% end %>
  <h5 class="mb-5">Hobbies</h4>
  <%= f.fields_for :hobbies do |ff| %>
    <div class="field">
      <%= ff.label :hobby, "Hobby", class: "label" %>
      <%= ff.text_field :name, hint: 'No special characters.', class: "input" %>
    </div>
  <% end %>
  <div class="field">
     <%= f.button :submit, class: "btn btn-primary w-full" %>
  </div>
<% end %>